### ISSUE TITLE
check in unit tests so they run during your build process

### ISSUE THREAD

**Issue by shehackspurple** [DevSlop/DevSlop.co#3]
check in unit tests so they run during your build process

**Comment by Carl-Hugo** [comment]
To make your CI pipeline easier to contribute to, have you considered adding an `azure-pipelines.yml` file to GitHub instead of using the GUI of Azure DevOps (assuming you are using Azure DevOps)?

If you are curious about that file, I googled you the following links:
- https://docs.microsoft.com/en-us/azure/devops/pipelines/get-started-yaml?view=azdevops
- https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/dotnet-core?view=azdevops&tabs=yaml

**Comment by shehackspurple** [comment]
This website is no longer in existence, closing issue.
